on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  buildAndDeploy:
    runs-on: ubuntu-latest

    env:
      NEXUS_USERNAME: ${{ }}
      NEXUS_PASSWORD: ${{ }}
      PLATFORM_USERNAME: ${{ }}
      PLATFORM_PASSWORD: ${{ }}
      SANDBOX_CLIENT_ID: ${{ }}
      SANDBOX_CLIENT_PASSWORD: ${{ }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup_java@v2
      with:
        java-version: '11'
        distributuion: 'adopt'
        cache:: 'maven'

    - name: Build with maven
      run: mvn clean -B package -s maven/settings.xml

    - name: Slack notifications
      uses: act10ns/slack@v1
      with:
        status: ${{ job.status }}
        steps: ${{ toJson(steps) }}
        channel: '#qamag'
      if: always()
  

